### ISSUE TITLE
Grout Recipe creates Flint instead

### ISSUE THREAD

**Issue by ghost** [asim0v/GamealitionPack#10]
Under specific circumstances, using the 1 clay, 1 sand, 1 gravel -> 2 grout recipe creates flint.

Steps to Reproduce:
1. Place 1 gravel block, 1 sand block, and 1 clay (not block) on a 3x3 crafting grid. 2 grout can be crafted. This was tested with a TiCon crafting station.
2. Place one more of each on the grid. Grout can still be crafted.
3. Place one more sand and clay on the grid, then place the gravel. The recipe changes from grout to flint.
4. Removing some of the sand or clay doesn't change the recipe. As long as there is at least 3 gravel, the recipe is always flint.

![](https://i.imgur.com/NmDHQVy.png)

![](https://i.imgur.com/n2Ebm2E.png)

**Comment by asim0v** [comment]
Thanks for the report, and sorry it took so long to reply.

This has been fixed in the update today to 1.3.11.
![fixed](https://i.imgur.com/pmFLaUF.png "fixed")
