### ISSUE TITLE
"Iron Plate" (AbyssalCraft) and "Iron Rod" (ImmEng) shares crafting recipe

### ISSUE THREAD

**Issue by ghost** [asim0v/GamealitionPack#11]
The Iron Plate from Abyssal Craft and Iron Rod from Immersive Engineering share the same crafting recipe. Two iron ingots in a 1x2 vertical line on the crafting grid. The recipe prefers the Iron Rods.

![](https://i.imgur.com/df2kXnm.png)

![](https://i.imgur.com/mNJovAo.png)

**Comment by asim0v** [comment]
I removed the recipe for the AbyssalCraft iron plate since none of the foods that can be made with it are balanced for Spice of Life and are way too OP. Easier to just disable the conflicting recipe rather than write a new one and then try to manually balance the food recipes.
