### ISSUE TITLE
Yellorite not being generated from Void Ore Miner

### ISSUE THREAD

**Issue by bales75** [asim0v/GamealitionPack#4]
After 6 hours I have still not generated a single yellorite ore block.  I just switched to a yellow lens and will check back tomorrow.

https://i.imgur.com/WAspeoV.png

**Comment by bales75** [comment]
And after another 15.5 hours with a yellow lens.  Still no Yellorite, 

https://i.imgur.com/tM7Cx80.png

**Comment by asim0v** [comment]
Thanks for reporting back. After looking into the bug reported for Environmental Tech, found t[his one that confirms it](https://github.com/ValkyrieofNight/EnvironmentalTech/issues/67). Additionally, this issue is fixed in the latest version.
